"""Generate the reader-facing README index of published articles.

This repository is where readers read the series, so it needs a front
door. This script builds one from the files themselves rather than from a
hand-maintained list, because a hand-maintained list drifts and the drift
is invisible until a reader clicks a dead link.

THE EMBARGO IS THE POINT. Only posts dated on or before the run date are
listed. A post written ahead of time exists in the working tree, is not
staged, and does not appear here. Regenerate on each post day, after
staging that day's files, and the index grows by exactly one day.

Titles are read from each file's first level-one heading. The editorial
audit header above the `---` marker is never read, so nothing internal
can leak into the index.

Run:      python3 tools/build_index.py            (writes README.md)
          python3 tools/build_index.py --check    (fails if stale)
          python3 tools/build_index.py --date 2026-09-12
Depends:  Python 3.8+ standard library.
Exit:     0 on success, 1 if --check finds the file stale, 2 on bad input.
"""

import argparse
import datetime as dt
import os
import re
import sys
from typing import Dict, List, NamedTuple, Optional, Sequence

REPO_BLOB = "https://github.com/QuantumindSSI/systemdesign/blob/main/"
POSTS_DIR = "posts"
ARCHIVE_DIR = "_archive"
OUTPUT = "README.md"

FILENAME = re.compile(
    r"^(?P<date>\d{4}-\d{2}-\d{2})-(?P<day>[a-z]{3})-(?P<rest>.+)\.md$"
)
HEADING = re.compile(r"^#\s+(.*?)\s*$")
SLOT_HINT = re.compile(r"\b(am|pm)\b")

# Files that live under posts/ but are production material rather than
# articles: platform teaser bundles and video shooting plans. They are not
# written for a reader arriving at this repository, so the index omits them.
NON_ARTICLE = re.compile(r"(?:^|-)(?:teasers|video-production-plan)$")

# Series start, used to number weeks the same way the calendar does.
WEEK_ONE_START = dt.date(2026, 8, 23)

HEADER = """# AI Engineering from Scratch

A hundred weeks of engineering writing, two posts a day, every day, published
here on the day they go out.

Every implementation the series discusses is written into this repository,
tested, and then read line by line in an article. Nothing is borrowed from
another repository and summarised. Everything runs on the Python standard
library, so you can clone this and execute any artifact with no install step.

```
python3 -m unittest discover -s tests -t .     # the library's test suite
python3 tools/publication_gate.py              # the rules this repo runs under
```

| Tree | What it holds |
|---|---|
| `posts/` | The articles, published on their day and not before |
| `lib/` | Reference implementations the articles walk through |
| `tests/` | The test suite behind `lib/` |
| `experiments/` | Runnable measurements quoted in specific articles |
| `data/` | Frozen corpora, so a quoted number stays reproducible |
| `tools/` | The gates that keep this repository honest |

Articles are listed below as they publish. Posts written ahead of their day
are deliberately absent: they are not committed until the morning they go out.

"""

FOOTER = """
---

Generated by `tools/build_index.py`. Regenerate after staging each day's posts.
"""


class Post(NamedTuple):
    """One published article, as the index needs it."""

    date: dt.date
    slot: str
    path: str
    title: str

    @property
    def week(self) -> int:
        """Calendar week number, counting the first week as 1."""
        return max(0, (self.date - WEEK_ONE_START).days // 7 + 1)


def read_title(path: str) -> Optional[str]:
    """Return the first level-one heading, or None if the file has none."""
    try:
        with open(path, encoding="utf-8") as handle:
            for line in handle:
                match = HEADING.match(line)
                if match:
                    return match.group(1)
    except OSError as exc:
        print(f"cannot read {path}: {exc}", file=sys.stderr)
        return None
    return None


def slot_of(rest: str) -> str:
    """Classify a filename tail as AM, PM, or a whole-day artifact."""
    match = SLOT_HINT.search(rest)
    if match:
        return match.group(1).upper()
    return "DAY"


def collect(root: str, today: dt.date) -> List[Post]:
    """Gather every published post, excluding the archive, sorted by date.

    Posts dated after `today` are omitted. That omission is the embargo.
    """
    posts: List[Post] = []
    posts_root = os.path.join(root, POSTS_DIR)
    if not os.path.isdir(posts_root):
        return posts
    for name in sorted(os.listdir(posts_root)):
        full = os.path.join(posts_root, name)
        if name == ARCHIVE_DIR or not os.path.isfile(full):
            continue
        match = FILENAME.match(name)
        if not match:
            continue
        if NON_ARTICLE.search(match.group("rest")):
            continue
        try:
            date = dt.date.fromisoformat(match.group("date"))
        except ValueError:
            continue
        if date > today:
            continue
        title = read_title(full)
        if title is None:
            continue
        posts.append(
            Post(date, slot_of(match.group("rest")),
                 f"{POSTS_DIR}/{name}", title)
        )
    return sorted(posts, key=lambda p: (p.date, p.slot, p.path))


def group_by_week(posts: Sequence[Post]) -> Dict[int, List[Post]]:
    """Bucket posts by calendar week, preserving order inside each bucket."""
    grouped: Dict[int, List[Post]] = {}
    for post in posts:
        grouped.setdefault(post.week, []).append(post)
    return grouped


def strip_prefix(title: str) -> str:
    """Drop the internal 'Week N · Day date ·' prefix from a heading."""
    parts = title.split("\u00b7")
    return parts[-1].strip() if len(parts) > 1 else title.strip()


def render(posts: Sequence[Post]) -> str:
    """Build the whole README body."""
    lines = [HEADER]
    if not posts:
        lines.append("No articles have published yet.\n")
        return "".join(lines) + FOOTER
    grouped = group_by_week(posts)
    for week in sorted(grouped, reverse=True):
        lines.append(f"## Week {week}\n\n")
        for post in grouped[week]:
            label = f"{post.date.isoformat()} {post.slot}"
            lines.append(
                f"- **{label}** [{strip_prefix(post.title)}]({REPO_BLOB}{post.path})\n"
            )
        lines.append("\n")
    return "".join(lines) + FOOTER


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--date", help="build the index as of this ISO date")
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the committed README is stale",
    )
    parser.add_argument(
        "--root",
        default=os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        help="repository root",
    )
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    """Build or verify the index. Returns the process exit code."""
    args = parse_args(argv)
    if args.date:
        try:
            today = dt.date.fromisoformat(args.date)
        except ValueError:
            print(f"--date must be ISO format, got {args.date!r}", file=sys.stderr)
            return 2
    else:
        today = dt.date.today()

    posts = collect(args.root, today)
    content = render(posts)
    destination = os.path.join(args.root, OUTPUT)

    if args.check:
        try:
            with open(destination, encoding="utf-8") as handle:
                current = handle.read()
        except OSError:
            print(f"{OUTPUT} does not exist. Run without --check.", file=sys.stderr)
            return 1
        if current != content:
            print(f"{OUTPUT} is stale. Run: python3 tools/build_index.py",
                  file=sys.stderr)
            return 1
        print(f"{OUTPUT} is current: {len(posts)} published article(s).")
        return 0

    with open(destination, "w", encoding="utf-8") as handle:
        handle.write(content)
    print(f"wrote {OUTPUT}: {len(posts)} published article(s) "
          f"as of {today.isoformat()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
